# Generated by Django 2.2.24 on 2022-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_theme_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(choices=[('Kanit', 'Kanit font'), ('Roboto', 'Roboto font'), ('Prompt', 'Prompt font')], default='green', max_length=3, verbose_name='Font'),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo_img_path',
            field=models.TextField(blank=True, help_text='This is image path logo.', verbose_name='Logo_image_path'),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo_text',
            field=models.TextField(blank=True, help_text='This is logo text.', verbose_name='Logo_text'),
        ),
    ]
